import { Pool } from 'pg';

import { logger } from '../utils/logger.js';

import type {
  PlatformConnectionInfo,
  PlatformDriver,
  ProjectDbHandle,
} from './driver.interface.js';

/**
 * Node-target driver — talks to projects generated by ReactAIClientConfiguration.
 *
 * Data-plane: opens a `pg` pool to the project's DB (URL from `credentials.databaseUrl`).
 * Control-plane → project backend: HTTP POST to `<baseUrl>/api/internal/actions/run`
 * with a service-credential header (`credentials.serviceToken`). The exact
 * endpoint is owned by the generated admin-backend; until the platform-repo
 * additions land, invokeAction is best-effort.
 */
interface NodeCredentials {
  databaseUrl?: string;
  serviceToken?: string;
}

const parseCredentials = (raw: unknown): NodeCredentials => {
  if (raw === null || typeof raw !== 'object') return {};
  const o = raw as Record<string, unknown>;
  return {
    databaseUrl: typeof o.databaseUrl === 'string' ? o.databaseUrl : undefined,
    serviceToken: typeof o.serviceToken === 'string' ? o.serviceToken : undefined,
  };
};

const wrapPool = (pool: Pool): ProjectDbHandle => ({
  async query<T = unknown>(sql: string, params: unknown[] = []): Promise<T[]> {
    const result = await pool.query(sql, params as never[]);
    return result.rows as T[];
  },
  async transaction<T>(fn: (tx: ProjectDbHandle) => Promise<T>): Promise<T> {
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      const txHandle: ProjectDbHandle = {
        async query<U = unknown>(sql: string, params: unknown[] = []): Promise<U[]> {
          const r = await client.query(sql, params as never[]);
          return r.rows as U[];
        },
        async transaction(): Promise<never> {
          throw new Error('nested transactions are not supported');
        },
        async close() {
          // no-op for the inner handle
        },
      };
      const result = await fn(txHandle);
      await client.query('COMMIT');
      return result;
    } catch (err) {
      await client.query('ROLLBACK').catch(() => { /* ignore */ });
      throw err;
    } finally {
      client.release();
    }
  },
  async close() {
    await pool.end();
  },
});

export class NodePlatformDriver implements PlatformDriver {
  public readonly targetType = 'NODE' as const;
  public readonly connection: PlatformConnectionInfo;
  private pool: Pool | null = null;
  private readonly creds: NodeCredentials;

  constructor(connection: PlatformConnectionInfo) {
    this.connection = connection;
    this.creds = parseCredentials(connection.credentials);
  }

  async getProjectDb(): Promise<ProjectDbHandle> {
    if (!this.creds.databaseUrl) {
      throw new Error(
        `PlatformConnection '${this.connection.projectSlug}' has no credentials.databaseUrl set; ` +
          'runners that need the project DB will fail until credentials are configured.',
      );
    }
    if (!this.pool) {
      this.pool = new Pool({
        connectionString: this.creds.databaseUrl,
        max: 4,
      });
    }
    return wrapPool(this.pool);
  }

  async invokeAction(input: {
    actionSlug: string;
    params: Record<string, unknown>;
    triggeredBy: string;
  }): Promise<{ success: boolean; result?: unknown; error?: string }> {
    if (!this.creds.serviceToken) {
      return {
        success: false,
        error:
          'PlatformConnection.credentials.serviceToken is not set; cannot invoke project actions.',
      };
    }
    const url = new URL('/api/internal/actions/run', this.connection.baseUrl);
    try {
      const resp = await fetch(url.toString(), {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          authorization: `Bearer ${this.creds.serviceToken}`,
          'x-project-id': this.connection.projectSlug,
        },
        body: JSON.stringify({
          actionSlug: input.actionSlug,
          params: input.params,
          triggeredBy: input.triggeredBy,
        }),
      });
      const text = await resp.text();
      let parsed: unknown;
      try {
        parsed = text ? JSON.parse(text) : null;
      } catch {
        parsed = text;
      }
      if (!resp.ok) {
        return {
          success: false,
          error: `project backend returned ${resp.status}`,
          result: parsed,
        };
      }
      return { success: true, result: parsed };
    } catch (err) {
      logger.error('NodePlatformDriver.invokeAction failed', {
        projectSlug: this.connection.projectSlug,
        actionSlug: input.actionSlug,
        error: err instanceof Error ? err.message : String(err),
      });
      return {
        success: false,
        error: err instanceof Error ? err.message : 'unknown invokeAction error',
      };
    }
  }

  async close(): Promise<void> {
    if (this.pool) {
      await this.pool.end();
      this.pool = null;
    }
  }
}
